events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    # Logs
    log_format log_per_virtualhost '[$host] $remote_addr [$time_local] $status "$request" $body_bytes_sent';
    access_log /dev/stdout log_per_virtualhost;

    server {
        listen 80;
        server_name l2-5.ephec-ti.be www.l2-5.ephec-ti.be;
        root /var/www/html; # Chemin simplifié
        
        location /.well-known/acme-challenge/ {
            try_files $uri =404;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name l2-5.ephec-ti.be www.l2-5.ephec-ti.be;

        root /var/www/html; # On pointe vers le build React
        index index.html;

        ssl_certificate /etc/letsencrypt/live/l2-5.ephec-ti.be/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/l2-5.ephec-ti.be/privkey.pem;

        # Gestion du routage React (indispensable pour React Router)
        location / {
            try_files $uri $uri/ /index.html;
        }

        # API Proxy
        location /api/ {
            resolver 127.0.0.11 valid=30s;
            set $backend_node projet_dev3-server-1;
            proxy_pass http://$backend_node:3000;
            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Swagger
        location /api-docs/ {
            resolver 127.0.0.11 valid=30s;
            set $backend_node projet_dev3-server-1;
            proxy_pass http://$backend_node:3000;
        }
    }
}